apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-secrets-finder-cron
spec:
  schedule: "${SCHEDULE}" #UTC
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 3600
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false" # if you have istio and don't want its sidecars
          labels:
            app: kube-secrets-finder-cron
          name: kube-secrets-finder-cron
        spec:
          serviceAccountName: view-secrets
          restartPolicy: Never
          imagePullSecrets:
          - name: ${YOUR_IMAGE_PULL_SECRET} # use your secret for docker registry
          containers:
          - image: ${YOUR_DOCKER_IMAGE} # change to your docker image name
            imagePullPolicy: Always
            name: kube-secrets-finder-cron
            env:
              - name: DEPLOY
                value: "${DEPLOY}"
              - name: WHERE_AM_I
                value: "${WHERE_AM_I}"
              - name: MAILSERVER
                value: "${MAILSERVER}"
              - name: ADDR_FROM
                value: "${ADDR_FROM}"
              - name: ADDR_TO
                value: "${ADDR_TO}"
